login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

login/models.py
from django.db import models

login/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Input your username'}))
	password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Input your password'}))

	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		user = auth.authenticate(username=username, password=password)
		if user is None:
			raise forms.ValidationError('Username or password is incorrect') # Throw exceptions
		else:
			self.cleaned_data['user'] = user
		return self.cleaned_data

class RegForm(forms.Form):
	username = forms.CharField(label='Username', 
							   max_length=30, 
							   min_length=3, 
							   widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Input your username (3-30 chars)'}))

	email = forms.EmailField(label='Email', 
							 widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Input your email'}))

	password = forms.CharField(label='Password', 
							   min_length=6, 
							   widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Input your password'}))

	password_again = forms.CharField(label='Input Password Again', 
									 min_length=6, 
									 widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Input your password again'}))

	# Verify if username is repeated
	def clean_username(self):
		username = self.cleaned_data['username']
		# if User.objects.filter(username=username).count():
		if User.objects.filter(username=username).exists():
			raise forms.ValidationError('Username has already existed')
		return username

	# Verify Email
	def clean_email(self):
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			raise forms.ValidationError('Email has already existed')
		return email

	# Verify password
	def clean_password_again(self):
		password = self.cleaned_data['password']
		password_again = self.cleaned_data['password_again']
		if password != password_again:
			raise forms.ValidationError('Password and password again are not same')
		return password_again

login/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.models import User

from .forms import LoginForm, RegForm

# Create your views here.
def login(request):

	if request.user.is_authenticated:
		return redirect(reverse('home'))

	if request.method == 'POST':
		login_form = LoginForm(request.POST)
		if login_form.is_valid():
			user = login_form.cleaned_data['user']
			auth.login(request, user)
			return redirect(reverse('dashboard:dashboard')) # Namespace is dashboard
	else:
		login_form = LoginForm()

	context = {}
	context['login_form'] = login_form
	return render(request, 'login/login.html', context)

def register(request):

	if request.user.is_authenticated:
		return redirect(reverse('home'))

	if request.method == 'POST':
		reg_form = RegForm(request.POST)
		if reg_form.is_valid():
			username = reg_form.cleaned_data['username']
			email = reg_form.cleaned_data['email']
			password = reg_form.cleaned_data['password']

			user = User.objects.create_user(username, email, password)
			user.save()

			user = auth.authenticate(username=username, password=password)
			auth.login(request, user)
			return redirect(reverse('dashboard:dashboard'))
	else:
		reg_form = RegForm()

	context = {}
	context['reg_form'] = reg_form

	return render(request, 'login/register.html', context)

def logout(request):
	auth.logout(request)
	return redirect(reverse('home'))

login/templates/login/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
  <!-- BASICS -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Homepage</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'home/css/isotope.css' %}" media="screen" />
  <link rel="stylesheet" href="{% static 'home/js/fancybox/jquery.fancybox.css' %}" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/bootstrap-theme.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <!-- skin -->
  <link rel="stylesheet" href="{% static 'home/skin/default.css' %}">
  <!-- =======================================================
    Theme Name: Amoeba
    Theme URL: https://bootstrapmade.com/free-one-page-bootstrap-template-amoeba/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
  <section id="header" class="appear"></section>
  <div class="navbar navbar-fixed-top" role="navigation" data-0="line-height:100px; height:100px; background-color:rgba(0,0,0,0.3);" data-300="line-height:60px; height:60px; background-color:rgba(0,0,0,1);">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="fa fa-bars color-white"></span>
          </button>
        <h1><a class="navbar-brand" href="index.html" data-0="line-height:90px;" data-300="line-height:50px;">      Query Relevant Online Tool
          </a></h1>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav" data-0="margin-top:20px;" data-300="margin-top:5px;">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li class="{% block nav_login_active %}{% endblock %}"><a href="{% url 'login:login' %}">Login</a></li>
          <li class="{% block nav_register_active %}{% endblock %}"><a href="{% url 'login:register' %}">Register</a></li>
        </ul>
      </div>
      <!--/.navbar-collapse -->
    </div>
  </div>

  <section class="featured" style="height: 80%">
    <div class="container">
      <div class="row mar-bot50">

          <div class="align-center">
            <h2 class="slogan">{% block slogan %}{% endblock %}</h2>
          </div>
          <div class="align-center">
            {% block content %}{% endblock %}
          </div>

      </div>
    </div>
  </section>

  <section id="footer" class="section footer">
    <div class="container">
      <div class="row animated opacity mar-bot20" data-andown="fadeIn" data-animation="animation">
        <div class="col-sm-12 align-center">
          <ul class="social-network social-circle">
            <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>

      <div class="row align-center copyright">
        <div class="col-sm-12">
          <p>Copyright &copy; Qinyu Liu</p>
          <div class="credits">
            <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX trail form: https://bootstrapmade.com/buy/?theme=Amoeba
            -->
            Designed by <a href="">BootstrapMade</a>
          </div>
        </div>
      </div>
    </div>

  </section>
  <a href="#header" class="scrollup"><i class="fa fa-chevron-up"></i></a>

  <script src="{% static 'home/js/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.js' %}"></script>
  <script src="{% static 'home/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.isotope.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static 'home/js/fancybox/jquery.fancybox.pack.js' %}"></script>
  <script src="{% static 'home/js/skrollr.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.scrollTo.js' %}"></script>
  <script src="{% static 'home/js/jquery.localScroll.js' %}"></script>
  <script src="{% static 'home/js/stellar.js' %}"></script>
  <script src="{% static 'home/js/jquery.appear.js' %}"></script>
  <script src="{% static 'home/js/main.js' %}"></script>
</body>

</html>

login/templates/login/login.html
{% extends 'login/base.html' %}
{# Has to load staticfiles again, as it cannot be extended from base.html #}
{% load staticfiles %}

{% block nav_login_active %}active{% endblock %}
{% block slogan %}Please Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Login</h3>
				</div>
				<div class="panel-body">
					<!-- If the action is empty, the action is redering to itself -->
					<form action="" method="POST">
						{% csrf_token %}
						{% for field in login_form %}
							<label for="{{ field.id_for_label }}">{{ field.label }}</label>
							{{ field }}
							<p class="text-danger">{{ field.errors.as_text }}</p>
						{% endfor %}
						<span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
						<input type="submit" name="login" class="btn btn-primary pull-right">
					</form>
				</div>
			</div>
			
		</div>
	</div>
</div>
{% endblock %}

login/templates/login/register.html
{% extends 'login/base.html' %}
{# Has to load staticfiles again, as it cannot be extended from base.html #}
{% load staticfiles %}

{% block nav_register_active %}active{% endblock %}
{% block slogan %}Welcome to Register{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4 col-xs-6 col-xs-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Register</h3>
				</div>
				<div class="panel-body">
					<!-- If the action is empty, the action is redering to itself -->
					<form action="" method="POST">
						{% csrf_token %}
						{% for field in reg_form %}
							<label for="{{ field.id_for_label }}">{{ field.label }}</label>
							{{ field }}
							<p class="text-danger">{{ field.errors.as_text }}</p>
						{% endfor %}
						<span class="pull-left text-danger">{{ reg_form.non_field_errors }}</span>
						<input type="submit" name="login" class="btn btn-primary pull-right">
					</form>
				</div>
			</div>
			
		</div>
	</div>
</div>
{% endblock %}