dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('file_upload', views.file_upload, name='file_upload'),
    path('my_files', views.my_files, name='my_files'),
    path('perform', views.perform, name='perform'),
    path('discovery', views.discovery, name='discovery'),
]

fileuploads/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'fileuploads'
urlpatterns = [
    path('test/', views.test, name='test'),
    path('upload_result/', views.upload_result, name='upload_result'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

dashboard/models.py
from django.db import models

fileuploads/models.py
import datetime
import os

from djongo import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

class SentenceItem(models.Model):
	_id = models.ObjectIdField()
	sentence = models.CharField(max_length=255)
	class Meta:
		abstract = True
	def __str__(self):
		return self.sentence

class File(models.Model):
	_id = models.ObjectIdField()
	file_name = models.CharField(max_length=200)
	file_path = models.CharField(max_length=200)
	# pub_date = models.DateTimeField('date published')
	created_time = models.DateTimeField(auto_now_add=True)
	# last_updated_time = models.DateTimeField(auto_now=True)
	file_content = models.ArrayModelField(model_container=SentenceItem,)

	def __str__(self):
		return self.file_name

class Directory(models.Model):
	_id = models.ObjectIdField()
	directory_name = models.CharField(max_length=200)
	# user = models.EmbeddedModelField(model_container=User,)
	owner = models.CharField(max_length=200)
	file = models.ArrayReferenceField(to=File, on_delete=models.CASCADE,)

	def __str__(self):
		return self.directory_name

class Profile(models.Model):
	_id = models.ObjectIdField()
	owner = models.CharField(max_length=200)
	directory = models.ArrayReferenceField(to=Directory, on_delete=models.DO_NOTHING,)

	def __str__(self):
		return self.owner

class QueryItem(models.Model):
	_id = models.ObjectIdField()
	items = models.CharField(max_length=255)
	support = models.CharField(max_length=100)
	weight = models.CharField(max_length=100)
	class Meta:
		abstract = True
	def __str__(self):
		return self.items

class ResultFile(models.Model):
	_id = models.ObjectIdField()
	file_name = models.CharField(max_length=200)
	file_path = models.CharField(max_length=200)
	owner = models.CharField(max_length=200)
	# pub_date = models.DateTimeField('date published')
	created_time = models.DateTimeField(auto_now_add=True)
	# last_updated_time = models.DateTimeField(auto_now=True)
	file_content = models.ArrayModelField(model_container=QueryItem,)

	def __str__(self):
		return self.file_name

fileuploads/forms.py
import operator
from django import forms
from IFN702.utils import validator_decimal, is_float
from django.db.models import ObjectDoesNotExist
from .models import ResultFile
# from django.core.validators import MaxValueValidator
# from captcha.fields import CaptchaField

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50, label="Name Your File (Set default leave empty)", required=False)
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={
    		'multiple': True, 
    		'class': 'form-control',
    		'id': 'chat_file',
    		'placeholder': 'Choose a file...',
    		}))

class ParameterForm(forms.Form):
	min_support = forms.DecimalField(label="Minimum Support", initial=1.0, decimal_places=3, required=True,  
				widget=forms.NumberInput(attrs={
					'class':'form-control', 
					'placeholder':'Minimum Support',
					}))
	threshold = forms.DecimalField(label="Threshold", initial=1.0, decimal_places=1, required=True,  
				widget=forms.NumberInput(attrs={
					'class':'form-control', 
					'placeholder':'Threshold'
					}))
	parameter3 = forms.DecimalField(label="parameter3", initial=1.0, decimal_places=1, required=True, 
				widget=forms.NumberInput(attrs={
					'class':'form-control', 
					'placeholder':'parameter3'
					}))
	query_input = forms.CharField(label="Query", max_length=128, required=True,
				widget=forms.TextInput(attrs={
					'class':'form-control', 
					'placeholder':'Please input your query'
					}))

	def clean_min_support(self):
		min_support = self.cleaned_data['min_support']
		if not is_float(min_support):
			raise forms.ValidationError('Your input has to be numbers')
		if not validator_decimal(min_support, 0, 1, 3):
			raise forms.ValidationError('Minimum support has to be [0, 1]')
		return min_support

	def clean_threshold(self):
		threshold = self.cleaned_data['threshold']
		if not is_float(threshold):
			raise forms.ValidationError('Your input has to be numbers')
		if not validator_decimal(threshold, 0, 2, 1):
			raise forms.ValidationError('Threshold has to be [0, 2]')
		return threshold

	def clean_parameter3(self):
		parameter3 = self.cleaned_data['parameter3']
		if not is_float(parameter3):
			raise forms.ValidationError('Your input has to be numbers')
		if not validator_decimal(parameter3, 0, 2, 1):
			raise forms.ValidationError('Parameter3 has to be [0, 1]')
		return parameter3


class SearchForm(forms.Form):

	Options1 = [('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equal To')]
	Options2 = [('contains', 'Contains'), ('eq', 'Equal To')]
	weight_input = forms.DecimalField(label="Weight", initial=0, required=True,  
				widget=forms.TextInput(attrs={
					'id': 'weight_input', 
					'name': 'weight_input', 
					'class':'form-control', 
					}))
	weight_select = forms.ChoiceField(label="Weight Operation", widget=forms.Select, choices=Options1)

	min_support_input = forms.DecimalField(label="Minimum Support", initial=0, required=True,  
				widget=forms.TextInput(attrs={
					'id': 'min_support_input', 
					'name': 'min_support_input', 
					'class':'form-control', 
					}))
	min_support_select = forms.ChoiceField(label="Minimum Support Operation", widget=forms.Select, choices=Options1)

	items_input = forms.CharField(label="Items", max_length=128, required=False,  
				widget=forms.TextInput(attrs={
					'id': 'items_input', 
					'name': 'items_input', 
					'class':'form-control', 
					}))
	items_select = forms.ChoiceField(label="Items Operation", widget=forms.Select, choices=Options2)

	def __init__(self, *args, **kwargs):
		if 'request' in kwargs:
			self.request = kwargs.pop('request')
		super(SearchForm, self).__init__(*args, **kwargs)

	# def clean_weight_input(self):
	# 	weight_input = self.cleaned_data['weight_input']
	# 	if not is_float(weight_input):
	# 		raise forms.ValidationError('Your input has to be numbers')

	# def clean_min_support_input(self):
	# 	min_support_input = self.cleaned_data['min_support_input']
	# 	if not is_float(min_support_input):
	# 		raise forms.ValidationError('Your input has to be numbers')

	def clean(self):

		def search(source, relate, target):
			ops = {
				'gt':operator.gt,
				'lt':operator.lt,
				'eq':operator.eq,
				'contains': operator.contains,
			}
			return ops[relate](source, target)

		error = ''
		weight_input = self.cleaned_data.get('weight_input', None)
		min_support_input = self.cleaned_data.get('min_support_input', None)
		items_input = self.cleaned_data['items_input']

		if weight_input == '':
			weight_input = 0
		if min_support_input == '':
			min_support_input = 0

		weight_select = self.cleaned_data['weight_select']
		min_support_select = self.cleaned_data['min_support_select']
		items_select = self.cleaned_data['items_select']

		if not (is_float(weight_input) and is_float(min_support_input)):
			raise forms.ValidationError('Your input has to be numbers. %s and %s are not.' % (weight_input, min_support_input))

		if error.strip() != '':
			raise forms.ValidationError(error)
		else:
			# Perform Search
			try:
				file_pk = self.request.GET.get('id', ResultFile.objects.first().pk)
				file = ResultFile.objects.get(owner=self.request.user.username, pk=file_pk)
				# For bootstrap-table
				table_with_weight = {}
				table_with_weight['filename'] = file.file_name
				table_with_weight['data'] = []

				table_without_weight = {}
				table_without_weight['filename'] = file.file_name
				table_without_weight['data'] = []

				# Iteratively search QueryItem objects
				contents = file.file_content
				for query_item in contents:
					# Generate the table without weight
					if float(query_item.weight) == 0.0:
						 # For bootstrap-table
						table_without_weight['data'].append({
						    'words': query_item.items,
						    'support': query_item.support
						    })

					# Generate the table with weight
					if search(float(query_item.weight), weight_select, float(weight_input)) and \
						search(float(query_item.support), min_support_select, float(min_support_input)) and \
						search(query_item.items, items_select, items_input):
						# Satisfied with the query
						 # For bootstrap-table
						table_with_weight['data'].append({
						    'words': query_item.items,
						    'weight': query_item.weight,
						    'support': query_item.support
						    })
						# raise forms.ValidationError("%s,%s,%s" % (query_item.items, query_item.weight, query_item.support))

				self.cleaned_data['table_with_weight'] = table_with_weight
				self.cleaned_data['table_without_weight'] = table_without_weight
			except ObjectDoesNotExist:
				raise forms.ValidationError('File target does not exist')
		return self.cleaned_data

dashboard/views.py
import json
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.urls import reverse
from django.conf import settings
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect

from fileuploads.forms import UploadFileForm, SearchForm, ParameterForm
from fileuploads.models import Directory, Profile, ResultFile
from fileuploads.utils import handle_file_upload, handle_result_file

# Create your views here.
def dashboard(request):
	if not request.user.is_authenticated:
		return redirect(reverse('home'))
	return render(request, 'dashboard/index.html')

def file_upload(request):
	context = {}
	data = {}

	if request.method == "POST":
		form_field = UploadFileForm(request.POST, request.FILES)
		if form_field.is_valid():
			file_check_results = handle_file_upload(request)
			data['status'] = 'SUCCESS'
			data['file_not_accepted'] = file_check_results['file_not_accepted']
			data['file_accepted'] = file_check_results['file_accepted']
		else:
			data['status'] = 'ERROR'
			data['messages'] = list(form_field.errors.values())[0]
		return JsonResponse(data)
	else:
		form_field = UploadFileForm()

	context['form_field'] = form_field
	return render(request, 'dashboard/file_upload.html', context)

def my_files(request):
	context = {}
	username = request.user.username
	profile = Profile.objects.filter(owner=username)
	directory = Directory.objects.filter(owner=username)

	folder = request.GET.get('folder', 'all')

	directories = []
	files = []
	for p in profile:
		directories += list(p.directory.all())
	if folder == 'all':
		for d in directory:
			files += list(d.file.all())
	else:
		for d in directory.filter(directory_name=folder):
			files += list(d.file.all())

	page_of_files, page_range = my_paginator(request, files)


	context['directories'] = directories
	context['page_of_files'] = page_of_files
	context['files'] = page_of_files.object_list
	context['page_range'] = page_range
	context['current_directory'] = folder

	return render(request, 'dashboard/my_files.html', context)

def my_paginator(request, objects):
	paginator = Paginator(objects, settings.FILE_FOR_EACH_PAGE)
	page_num = request.GET.get('page', 1)
	page_of_objects = paginator.get_page(page_num)

	current_page_num = page_of_objects.number
	page_range = list(range(max(current_page_num - 2,  1), current_page_num)) + \
				list(range(current_page_num, min(paginator.num_pages, current_page_num + 2) + 1))

	# Add ... to pagination
	if page_range[0] - 1 >= 2:
		page_range.insert(0, '...')
	if paginator.num_pages - page_range[-1] >= 2:
		page_range.append('...')

	# Add first and last page number
	if page_range[0] != 1:
		page_range.insert(0, 1)
	if page_range[-1] != paginator.num_pages:
		page_range.append(paginator.num_pages)

	return page_of_objects, page_range

def perform(request):
	context = {}
	if request.method == "POST":
		file_selected = request.POST.get("file_selected", "")
		context['file_selected'] = file_selected
		context['parameter_form'] = ParameterForm()
	return render(request, 'dashboard/perform.html', context)

def discovery(request):
	context = {}
	data = {}
	file_pk = request.GET.get('id', '')
	if file_pk and request.method == "POST":
		search_field = SearchForm(request.POST, request=request)
		if search_field.is_valid():
			context['table_with_weight'] = json.dumps(search_field.cleaned_data['table_with_weight']['data'])
			context['table_without_weight'] = json.dumps(search_field.cleaned_data['table_without_weight']['data'])
	    # Filter function goes here
		    # request.POST.get("weight", "")
		    # request.POST.get("weight_input", "")
		    # request.POST.get("min_support", "")
		    # request.POST.get("min_support_input", "")
		    # request.POST.get("items", "")
		    # request.POST.get("items_input", "")
	else:
		search_field = SearchForm()

	context['search_field'] = search_field
	result_files = ResultFile.objects.filter(owner=request.user.username)
	context['result_files'] = result_files
	form_field = UploadFileForm()
	context['form_field'] = form_field
	context['file_selected'] = file_pk
	return render(request, 'dashboard/discovery.html', context)

fileuploads/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.conf import settings

from suit_dashboard.views import DashboardView

from . import forms
from .models import File, Directory, Profile
from .forms import UploadFileForm
from .utils import handle_result_file

import os
import time
import zipfile

def validator_decimal(num, min, max, decimal_places):
    if float(num) >= float(min) and float(num) <= float(max):
        return round(float(num), decimal_places)
    return False

# Page of Result Files Uploads
def upload_result(request):
    context = {}
    data = {}
    if request.method == "POST":
        form_field = forms.UploadFileForm(request.POST, request.FILES)
        if form_field.is_valid():
            file_obj = handle_result_file(request)
            data['status'] = 'SUCCESS'
            data['table_data'] = file_obj['data']
            # return render(request, 'fileuploads/show_result.html', context)
        else:
            data['status'] = 'ERROR'
            data['messages'] = list(form_field.errors.values())[0]
        return JsonResponse(data)
    else:
        form_field = forms.UploadFileForm()
    context['form_field'] = form_field
    return render(request, 'dashboard/discovery.html', context)

def test(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context = {'latest_question_list': latest_question_list}
    title = {'title': 'TestPage'}
    return render(request, 'fileuploads/test.html', title)

fileuploads/templates/fileuploads/dashboard.html
{% extends 'fileuploads/base.html' %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}

<div class="col-xs-4 col-xs-offset-4">
  <h3> Welcome to Query Relevant Tool Dashboard</h3>
</div>

{% endblock %}
{% block page_header %} Upload {% endblock %}
{% block page_description %} File Upload {% endblock %}

fileuploads/templates/fileuploads/list.html
{% extends 'fileuploads/base.html' %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}

{% block nav_list_active %}active{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-table.min.css' %}">
{% endblock %}
{% block content %}
<div class="panel-body" style="padding-bottom:0px;">
    <div class="panel panel-default">
      <div class="panel-heading">Search Conditions</div>
      <div class="panel-body">
        <form id="formSearch" class="form-horizontal">
          <div class="form-group" style="margin-top:15px">
            <label class="control-label col-sm-1" for="txt_search_name">Name</label>
            <div class="col-sm-3">
              <input type="text" class="form-control" id="txt_search_name">
            </div>
            <label class="control-label col-sm-1" for="txt_search_statu">Parameter1</label>
            <div class="col-sm-3">
              <input type="text" class="form-control" id="txt_search_statu">
            </div>
            <div class="col-sm-4" style="text-align:left;">
              <button type="button" style="margin-left:50px" id="btn_query" class="btn btn-primary">Search</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div id="toolbar" class="btn-group">
      <button id="btn_add" type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add
      </button>
      <button id="btn_edit" type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>Edit
      </button>
      <button id="btn_delete" type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>Delete
      </button>
    </div>
    <table id="category_table">
    	<!-- {% if latest_file_list %}
    	    <ul>
    	    {% for file in latest_file_list %}
    	        <li><a href="#">{{ file.file_name }}</a> &nbsp;&nbsp;&nbsp; <button type="button" class="btn btn-primary">Download</button></li>
    	    {% endfor %}
    	    </ul>
    	{% else %}
    	    <p>No files are available.</p>
    	{% endif %} -->
    </table>
    <h1>{{result}}</h1>
  </div>
</div><!-- ./end main-container-->
{% endblock %}
{% block script %}
<script type="text/javascript" src="{% static 'js/bootstrap-table.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-table.zh_CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/category_list.js' %}"></script>
{% endblock %}
{% block page_header %} List {% endblock %}
{% block page_description %} File List {% endblock %}

fileuploads/templates/fileuploads/show_result.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{{ message }}
</body>
</html>

fileuploads/templates/fileuploads/upload_result.html
{% extends 'fileuploads/base.html' %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}

{% block nav_upload_active %}active{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap_table/bootstrap-table.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-editable.css' %} ">
{% endblock %}

{% block content %}

<!-- main-container start -->
<div class="iner-fluid main-container">
  <div class="panel-body" style="padding-bottom:0px;">
    <div class="panel panel-default">
      <div class="panel-heading">File Upload</div>
      <div class="panel-body">
        <form id="upload_form" class="form-inline" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <label class="sr-only" for="chat_file">File upload</label>
            <div class="input-group">
              {% for field in form_field %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <p class="text-danger">{{ field.errors.as_text }}</p>
              {% endfor %}
              <span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
            </div>
          </div>
          <div class="row" style="margin-top:2em;">
            <span id="upload_error" class="text-success pull-left"></span>
            <input type="submit" class="btn btn-success w90" value="Upload">
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="panel-body" style="padding-bottom:0px;">
    <div class="panel panel-default">
      <div class="panel-heading">Table</div>
      <div class="panel-body">
        <div id="toolbar">
    <!--       <button id="remove" class="btn btn-danger" disabled>
            <i class="glyphicon glyphicon-remove"></i> Delete
          </button> -->
        </div>
        <table id="table"
               data-toolbar="#toolbar"
               data-search="true"
               data-show-refresh="true"
               data-show-columns="true"
               data-show-export="true"
               data-detail-view="true"
               data-detail-formatter="detailFormatter"
               data-minimum-count-columns="2"
               data-show-pagination-switch="true"
               data-pagination="true"
               data-id-field="id"
               data-page-list="[10, 25, 50, 100, ALL]"
               data-show-footer="false"
               data-side-pagination="client"
               data-response-handler="responseHandler">
        </table>
      </div>
    </div>
  </div>
</div><!-- ./end main-container-->

<!-- loading start -->
<div class="modal fade" id="loading" tabindex="-1" role="dialog">
  <div class="modal-body">
    <div class="loadEffect">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>
    <div class="loading-text" id="loading_text"></div>
  </div>
</div><!-- ./end loading -->
<!-- affirm -->
<div id="affirm_box">
{#    <div id="title_box"><span id="title_text">Reminder</span>#}
{#      <span id="affirm_close">&times;</span>#}
{#    </div>#}
  <div id="content_box"></div>
</div><!--./end -->

{% endblock %}
{% block page_header %} Upload {% endblock %}
{% block page_description %} File Upload {% endblock %}

{% block script %}
<script src="{% static 'bootstrap_table/bootstrap-table.min.js' %}"></script>
<script src="{% static 'bootstrap_table/bootstrap-table-zh-CN.min.js' %}"></script>
<script src="{% static 'bootstrap_table/bootstrap-table-export.js' %}"></script>
<script src="{% static 'bootstrap_table/tableExport.js' %}"></script>
<script src="{% static 'bootstrap_table/bootstrap-table-editable.js' %}"></script>
<script src="{% static 'bootstrap_table/bootstrap-editable.js' %}"></script>

<script>
  var $table = $('#table'),
      $remove = $('#remove'),
      selections = [];
      table_data = [];

  function initTable() {
    $table.bootstrapTable({
      height: getHeight(),
      columns: [
        [
          {
            field: 'state',
            checkbox: true,
            rowspan: 2,
            align: 'center',
            valign: 'middle'
          }, {
            title: 'Item Detail',
            colspan: 3,
            align: 'center'
          }
        ],
        [
          {
            field: 'words',
            title: 'Itemset',
            sortable: true,
            editable: true,
            footerFormatter: totalNameFormatter,
            align: 'center'
          }, {
            field: 'support',
            title: 'Support',
            sortable: true,
            editable: true,
            footerFormatter: totalNameFormatter,
            align: 'center'
          }, {
            field: 'weight',
            title: 'Weight',
            sortable: true,
            editable: true,
            footerFormatter: totalNameFormatter,
            align: 'center'
          }
        ]
      ],
      data: table_data,
    });
    // sometimes footer render error.
    setTimeout(function () {
        $table.bootstrapTable('resetView');
    }, 200);
    $table.on('check.bs.table uncheck.bs.table ' +
              'check-all.bs.table uncheck-all.bs.table', function () {
        $remove.prop('disabled', !$table.bootstrapTable('getSelections').length);

        // save your data, here just save the current page
        selections = getIdSelections();
        // push or splice the selections if you want to save all data selections
    });
    $table.on('expand-row.bs.table', function (e, index, row, $detail) {
        if (index % 2 == 1) {
            $detail.html('Loading from ajax request...');
            $.get('LICENSE', function (res) {
                $detail.html(res.replace(/\n/g, '<br>'));
            });
        }
    });
    $table.on('all.bs.table', function (e, name, args) {
        console.log(name, args);
    });
    $remove.click(function () {
      var ids = getIdSelections();
      $table.bootstrapTable('remove', {
        field: 'id',
        values: ids
      });
      $remove.prop('disabled', true);
    });
    $(window).resize(function () {
        $table.bootstrapTable('resetView', {
            height: getHeight()
        });
    });
  }

  function getIdSelections() {
      return $.map($table.bootstrapTable('getSelections'), function (row) {
          return row.id
      });
  }

  function responseHandler(res) {
      $.each(res.rows, function (i, row) {
          row.state = $.inArray(row.id, selections) !== -1;
      });
      return res;
  }

  function detailFormatter(index, row) {
      var html = [];
      $.each(row, function (key, value) {
          html.push('<p><b>' + key + ':</b> ' + value + '</p>');
      });
      return html.join('');
  }

  function operateFormatter(value, row, index) {
    return [
        '<a class="like" href="javascript:void(0)" title="Like">',
        '<i class="glyphicon glyphicon-heart"></i>',
        '</a>  ',
        '<a class="remove" href="javascript:void(0)" title="Remove">',
        '<i class="glyphicon glyphicon-remove"></i>',
        '</a>'
    ].join('');
  }

  window.operateEvents = {
      'click .like': function (e, value, row, index) {
          alert('You click like action, row: ' + JSON.stringify(row));
      },
      'click .remove': function (e, value, row, index) {
          $table.bootstrapTable('remove', {
              field: 'id',
              values: [row.id]
          });
      }
  };

  function totalTextFormatter(data) {
      return 'Total';
  }

  function totalNameFormatter(data) {
      return data.length;
  }

  function totalPriceFormatter(data) {
      var total = 0;
      $.each(data, function (i, row) {
          total += +(row.price.substring(1));
      });
      return '$' + total;
  }

  function getHeight() {
      return $(window).height() - $('h1').outerHeight(true);
  }

  // $(function () {
  //   initTable()
  // })
</script>

<script type="text/javascript">
  $("#upload_form").submit(function() {
      // Front-end empty check
      // Empty error message first
      $("#upload_error").text('');

      // Async submit
      var data = new FormData($(this).get(0));
      $.ajax({
        url: "{% url 'fileuploads:upload_result' %}",
        type: "POST",
        data: data,
        cache: false,
        processData: false,
        contentType: false,
        success: function(data) {
          console.log(data);
          if(data['status'] == 'SUCCESS') {
            // Insert the new comment
            $("#upload_error").text('Your file has been successfully uploaded');
            table_data = data['table_data'];
            initTable();
          } else {
            // Display error messages
            $("#comment_error").text(data['messages']);
          }
          
        },
        error: function(xhr) {
          console.log(xhr);
        }
      });
      return false;
    });
</script>

{% endblock %}