dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('file_upload', views.file_upload, name='file_upload'),
    path('my_files', views.my_files, name='my_files'),
    path('perform', views.perform, name='perform'),
    path('discovery', views.discovery, name='discovery'),
]

fileuploads/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'fileuploads'
urlpatterns = [
    path('test/', views.test, name='test'),
    path('upload_result/', views.upload_result, name='upload_result'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

dashboard/models.py
from django.db import models

fileuploads/models.py
import datetime
import os

from djongo import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

class SentenceItem(models.Model):
	_id = models.ObjectIdField()
	sentence = models.CharField(max_length=255)
	class Meta:
		abstract = True
	def __str__(self):
		return self.sentence

class File(models.Model):
	_id = models.ObjectIdField()
	file_name = models.CharField(max_length=200)
	file_path = models.CharField(max_length=200)
	# pub_date = models.DateTimeField('date published')
	created_time = models.DateTimeField(auto_now_add=True)
	# last_updated_time = models.DateTimeField(auto_now=True)
	file_content = models.ArrayModelField(model_container=SentenceItem,)

	def __str__(self):
		return self.file_name

class Directory(models.Model):
	_id = models.ObjectIdField()
	directory_name = models.CharField(max_length=200)
	# user = models.EmbeddedModelField(model_container=User,)
	owner = models.CharField(max_length=200)
	file = models.ArrayReferenceField(to=File, on_delete=models.CASCADE,)

	def __str__(self):
		return self.directory_name

class Profile(models.Model):
	_id = models.ObjectIdField()
	owner = models.CharField(max_length=200)
	directory = models.ArrayReferenceField(to=Directory, on_delete=models.DO_NOTHING,)

	def __str__(self):
		return self.owner

class QueryItem(models.Model):
	_id = models.ObjectIdField()
	items = models.CharField(max_length=255)
	support = models.CharField(max_length=100)
	weight = models.CharField(max_length=100)
	class Meta:
		abstract = True
	def __str__(self):
		return self.items

class ResultFile(models.Model):
	_id = models.ObjectIdField()
	file_name = models.CharField(max_length=200)
	file_path = models.CharField(max_length=200)
	owner = models.CharField(max_length=200)
	# pub_date = models.DateTimeField('date published')
	created_time = models.DateTimeField(auto_now_add=True)
	# last_updated_time = models.DateTimeField(auto_now=True)
	file_content = models.ArrayModelField(model_container=QueryItem,)

	def __str__(self):
		return self.file_name

fileuploads/forms.py
import operator
from django import forms
from IFN702.utils import validator_decimal, is_float
from django.db.models import ObjectDoesNotExist
from .models import ResultFile
# from django.core.validators import MaxValueValidator
# from captcha.fields import CaptchaField

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50, label="Name Your File (Set default leave empty)", required=False)
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={
    		'multiple': True, 
    		'class': 'form-control',
    		'id': 'chat_file',
    		'placeholder': 'Choose a file...',
    		}))

class ParameterForm(forms.Form):
	min_support = forms.DecimalField(label="Minimum Support", initial=1.0, decimal_places=3, required=True,  
				widget=forms.NumberInput(attrs={
					'class':'form-control', 
					'placeholder':'Minimum Support',
					}))
	threshold = forms.DecimalField(label="Threshold", initial=1.0, decimal_places=1, required=True,  
				widget=forms.NumberInput(attrs={
					'class':'form-control', 
					'placeholder':'Threshold'
					}))
	parameter3 = forms.DecimalField(label="parameter3", initial=1.0, decimal_places=1, required=True, 
				widget=forms.NumberInput(attrs={
					'class':'form-control', 
					'placeholder':'parameter3'
					}))
	query_input = forms.CharField(label="Query", max_length=128, required=True,
				widget=forms.TextInput(attrs={
					'class':'form-control', 
					'placeholder':'Please input your query'
					}))

	def clean_min_support(self):
		min_support = self.cleaned_data['min_support']
		if not is_float(min_support):
			raise forms.ValidationError('Your input has to be numbers')
		if not validator_decimal(min_support, 0, 1, 3):
			raise forms.ValidationError('Minimum support has to be [0, 1]')
		return min_support

	def clean_threshold(self):
		threshold = self.cleaned_data['threshold']
		if not is_float(threshold):
			raise forms.ValidationError('Your input has to be numbers')
		if not validator_decimal(threshold, 0, 2, 1):
			raise forms.ValidationError('Threshold has to be [0, 2]')
		return threshold

	def clean_parameter3(self):
		parameter3 = self.cleaned_data['parameter3']
		if not is_float(parameter3):
			raise forms.ValidationError('Your input has to be numbers')
		if not validator_decimal(parameter3, 0, 2, 1):
			raise forms.ValidationError('Parameter3 has to be [0, 1]')
		return parameter3


class SearchForm(forms.Form):

	Options1 = [('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equal To')]
	Options2 = [('contains', 'Contains'), ('eq', 'Equal To')]
	weight_input = forms.DecimalField(label="Weight", initial=0, required=True,  
				widget=forms.TextInput(attrs={
					'id': 'weight_input', 
					'name': 'weight_input', 
					'class':'form-control', 
					}))
	weight_select = forms.ChoiceField(label="Weight Operation", widget=forms.Select, choices=Options1)

	min_support_input = forms.DecimalField(label="Minimum Support", initial=0, required=True,  
				widget=forms.TextInput(attrs={
					'id': 'min_support_input', 
					'name': 'min_support_input', 
					'class':'form-control', 
					}))
	min_support_select = forms.ChoiceField(label="Minimum Support Operation", widget=forms.Select, choices=Options1)

	items_input = forms.CharField(label="Items", max_length=128, required=False,  
				widget=forms.TextInput(attrs={
					'id': 'items_input', 
					'name': 'items_input', 
					'class':'form-control', 
					}))
	items_select = forms.ChoiceField(label="Items Operation", widget=forms.Select, choices=Options2)

	def __init__(self, *args, **kwargs):
		if 'request' in kwargs:
			self.request = kwargs.pop('request')
		super(SearchForm, self).__init__(*args, **kwargs)

	# def clean_weight_input(self):
	# 	weight_input = self.cleaned_data['weight_input']
	# 	if not is_float(weight_input):
	# 		raise forms.ValidationError('Your input has to be numbers')

	# def clean_min_support_input(self):
	# 	min_support_input = self.cleaned_data['min_support_input']
	# 	if not is_float(min_support_input):
	# 		raise forms.ValidationError('Your input has to be numbers')

	def clean(self):

		def search(source, relate, target):
			ops = {
				'gt':operator.gt,
				'lt':operator.lt,
				'eq':operator.eq,
				'contains': operator.contains,
			}
			return ops[relate](source, target)

		error = ''
		weight_input = self.cleaned_data.get('weight_input', None)
		min_support_input = self.cleaned_data.get('min_support_input', None)
		items_input = self.cleaned_data['items_input']

		if weight_input == '':
			weight_input = 0
		if min_support_input == '':
			min_support_input = 0

		weight_select = self.cleaned_data['weight_select']
		min_support_select = self.cleaned_data['min_support_select']
		items_select = self.cleaned_data['items_select']

		if not (is_float(weight_input) and is_float(min_support_input)):
			raise forms.ValidationError('Your input has to be numbers. %s and %s are not.' % (weight_input, min_support_input))

		if error.strip() != '':
			raise forms.ValidationError(error)
		else:
			# Perform Search
			try:
				file_pk = self.request.GET.get('id', ResultFile.objects.first().pk)
				file = ResultFile.objects.get(owner=self.request.user.username, pk=file_pk)
				# For bootstrap-table
				table_with_weight = {}
				table_with_weight['filename'] = file.file_name
				table_with_weight['data'] = []

				table_without_weight = {}
				table_without_weight['filename'] = file.file_name
				table_without_weight['data'] = []

				# Iteratively search QueryItem objects
				contents = file.file_content
				for query_item in contents:
					# Generate the table without weight
					if float(query_item.weight) == 0.0:
						 # For bootstrap-table
						table_without_weight['data'].append({
						    'words': query_item.items,
						    'support': query_item.support
						    })

					# Generate the table with weight
					if search(float(query_item.weight), weight_select, float(weight_input)) and \
						search(float(query_item.support), min_support_select, float(min_support_input)) and \
						search(query_item.items, items_select, items_input):
						# Satisfied with the query
						 # For bootstrap-table
						table_with_weight['data'].append({
						    'words': query_item.items,
						    'weight': query_item.weight,
						    'support': query_item.support
						    })
						# raise forms.ValidationError("%s,%s,%s" % (query_item.items, query_item.weight, query_item.support))

				self.cleaned_data['table_with_weight'] = table_with_weight
				self.cleaned_data['table_without_weight'] = table_without_weight
			except ObjectDoesNotExist:
				raise forms.ValidationError('File target does not exist')
		return self.cleaned_data

dashboard/views.py
import json
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.urls import reverse
from django.conf import settings
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect

from fileuploads.forms import UploadFileForm, SearchForm, ParameterForm
from fileuploads.models import Directory, Profile, ResultFile
from fileuploads.utils import handle_file_upload, handle_result_file

# Create your views here.
def dashboard(request):
	if not request.user.is_authenticated:
		return redirect(reverse('home'))
	return render(request, 'dashboard/index.html')

def file_upload(request):
	context = {}
	data = {}

	if request.method == "POST":
		form_field = UploadFileForm(request.POST, request.FILES)
		if form_field.is_valid():
			file_check_results = handle_file_upload(request)
			data['status'] = 'SUCCESS'
			data['file_not_accepted'] = file_check_results['file_not_accepted']
			data['file_accepted'] = file_check_results['file_accepted']
		else:
			data['status'] = 'ERROR'
			data['messages'] = list(form_field.errors.values())[0]
		return JsonResponse(data)
	else:
		form_field = UploadFileForm()

	context['form_field'] = form_field
	return render(request, 'dashboard/file_upload.html', context)

def my_files(request):
	context = {}
	username = request.user.username
	profile = Profile.objects.filter(owner=username)
	directory = Directory.objects.filter(owner=username)

	folder = request.GET.get('folder', 'all')

	directories = []
	files = []
	for p in profile:
		directories += list(p.directory.all())
	if folder == 'all':
		for d in directory:
			files += list(d.file.all())
	else:
		for d in directory.filter(directory_name=folder):
			files += list(d.file.all())

	page_of_files, page_range = my_paginator(request, files)


	context['directories'] = directories
	context['page_of_files'] = page_of_files
	context['files'] = page_of_files.object_list
	context['page_range'] = page_range
	context['current_directory'] = folder

	return render(request, 'dashboard/my_files.html', context)

def my_paginator(request, objects):
	paginator = Paginator(objects, settings.FILE_FOR_EACH_PAGE)
	page_num = request.GET.get('page', 1)
	page_of_objects = paginator.get_page(page_num)

	current_page_num = page_of_objects.number
	page_range = list(range(max(current_page_num - 2,  1), current_page_num)) + \
				list(range(current_page_num, min(paginator.num_pages, current_page_num + 2) + 1))

	# Add ... to pagination
	if page_range[0] - 1 >= 2:
		page_range.insert(0, '...')
	if paginator.num_pages - page_range[-1] >= 2:
		page_range.append('...')

	# Add first and last page number
	if page_range[0] != 1:
		page_range.insert(0, 1)
	if page_range[-1] != paginator.num_pages:
		page_range.append(paginator.num_pages)

	return page_of_objects, page_range

def perform(request):
	context = {}
	if request.method == "POST":
		file_selected = request.POST.get("file_selected", "")
		context['file_selected'] = file_selected
		context['parameter_form'] = ParameterForm()
	return render(request, 'dashboard/perform.html', context)

def discovery(request):
	context = {}
	data = {}
	file_pk = request.GET.get('id', '')
	if file_pk and request.method == "POST":
		search_field = SearchForm(request.POST, request=request)
		if search_field.is_valid():
			context['table_with_weight'] = json.dumps(search_field.cleaned_data['table_with_weight']['data'])
			context['table_without_weight'] = json.dumps(search_field.cleaned_data['table_without_weight']['data'])
	    # Filter function goes here
		    # request.POST.get("weight", "")
		    # request.POST.get("weight_input", "")
		    # request.POST.get("min_support", "")
		    # request.POST.get("min_support_input", "")
		    # request.POST.get("items", "")
		    # request.POST.get("items_input", "")
	else:
		search_field = SearchForm()

	context['search_field'] = search_field
	result_files = ResultFile.objects.filter(owner=request.user.username)
	context['result_files'] = result_files
	form_field = UploadFileForm()
	context['form_field'] = form_field
	context['file_selected'] = file_pk
	return render(request, 'dashboard/discovery.html', context)

fileuploads/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.conf import settings

from suit_dashboard.views import DashboardView

from . import forms
from .models import File, Directory, Profile
from .forms import UploadFileForm
from .utils import handle_result_file

import os
import time
import zipfile

def validator_decimal(num, min, max, decimal_places):
    if float(num) >= float(min) and float(num) <= float(max):
        return round(float(num), decimal_places)
    return False

# Page of Result Files Uploads
def upload_result(request):
    context = {}
    data = {}
    if request.method == "POST":
        form_field = forms.UploadFileForm(request.POST, request.FILES)
        if form_field.is_valid():
            file_obj = handle_result_file(request)
            data['status'] = 'SUCCESS'
            data['table_data'] = file_obj['data']
            # return render(request, 'fileuploads/show_result.html', context)
        else:
            data['status'] = 'ERROR'
            data['messages'] = list(form_field.errors.values())[0]
        return JsonResponse(data)
    else:
        form_field = forms.UploadFileForm()
    context['form_field'] = form_field
    return render(request, 'dashboard/discovery.html', context)

def test(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # context = {'latest_question_list': latest_question_list}
    title = {'title': 'TestPage'}
    return render(request, 'fileuploads/test.html', title)

dashboard/templates/dashboard/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}My Dashboard{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'dashboard/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'dashboard/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'dashboard/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dashboard/dist/css/AdminLTE.css' %}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{% static 'dashboard/dist/css/skins/skin-blue.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  {% block css %}{% endblock %}

</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>Q</b>R</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>QR</b>TOOL</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <!-- <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"> -->
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">Current User: {{ user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'dist/img/avatar5.png' %}" class="img-circle" alt="User Image">

                <p>
                  {{ user.username }}
                  <small></small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
        <!--         <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div> -->
                <div class="pull-right">
                  <a href="{% url 'login:logout' %}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img id="sidebar_user_img" src="{% static 'dist/img/avatar5.png' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ user.username }}</p>
          <!-- Status -->
          <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
        </div>
      </div>

      <!-- search form (Optional) -->
     <!--  <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
        </div>
      </form> -->
      <!-- /.search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Navigation</li>
        <li class="{% block nav_home_active %}{% endblock %}"><a href="{% url 'dashboard:dashboard' %}"><i class="fa fa-link"></i> <span>Home</span></a></li>
        <!-- Optionally, you can add icons to the links -->
        <li class="{% block nav_upload_active %}{% endblock %}"><a href="{% url 'dashboard:file_upload' %}"><i class="fa fa-link"></i> <span>Upload Files</span></a></li>
        <li class="{% block nav_files_active %}{% endblock %}"><a href="{% url 'dashboard:my_files' %}"><i class="fa fa-link"></i> <span>My Files</span></a></li>
        <li class="{% block nav_perform_active %}{% endblock %}"><a href="{% url 'dashboard:perform' %}"><i class="fa fa-link"></i> <span>Perform</span></a></li>
        <li class="{% block nav_discovery_active %}{% endblock %}"><a href="{% url 'dashboard:discovery' %}"><i class="fa fa-link"></i> <span>Results Discovery</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block page_header %}Page Header{% endblock %}
        <small>{% block page_description %}Optional description{% endblock %}</small>
      </h1>
      <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
      </ol> -->
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

      {% block content %}{% endblock %}

      <!--------------------------
        | Your Page Content Here |
        -------------------------->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Qinyu Liu (N9325247)
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <!-- <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul> -->
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Back to Home</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="{% url 'home' %}">
              <h4 class="control-sidebar-subheading">
                Homepage
              </h4>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Display User Image
              <input id="user_img_display" type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Display your image on dashboard
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'dashboard/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/dist/js/adminlte.min.js' %}"></script>

<script type="text/javascript">
  $('#user_img_display').change(function() {
    if (this.checked) {
      $('#sidebar_user_img').show()
    }else {
      $('#sidebar_user_img').hide()
    }
  });
</script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
{% block script %}{% endblock %}

</body>
</html>

dashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}

<div class="col-xs-4 col-xs-offset-4">
  <h3> Welcome to Query Relevant Tool Dashboard</h3>
</div>

{% endblock %}
{% block page_header %} Home {% endblock %}
{% block page_description %} welcome page {% endblock %}

dashboard/templates/dashboard/perform.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}

{% block nav_perform_active %}active{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap_table/bootstrap-table.min.css' %}">
{% endblock %}

{% block page_header %} Perform {% endblock %}
{% block page_description %} Perform the algorithm {% endblock %}

{% block content %}

{% if file_selected %}
	<div class="container">
		<div class="row">
			<h3 class="text-success">Selected Files: {{ file_selected|truncatechars:50 }}</h3>
		</div>
		<div class="row">
			<div class="col-md-6 col-xs-8">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">Register</h3>
					</div>
					<div class="panel-body">
						<!-- If the action is empty, the action is redering to itself -->
						<form action="" method="POST">
							{% csrf_token %}
							{% for field in parameter_form %}
								<div class="form-group">
								  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
								  {{ field }}
								  <p class="text-danger">{{ field.errors.as_text }}</p>
								</div>
							{% endfor %}
							<span class="pull-left text-danger">{{ reg_form.non_field_errors }}</span>
							<input type="submit" name="execute" value="Execute" class="btn btn-primary pull-right">
						</form>
					</div>
				</div>
				
			</div>
		</div>
	</div>

{% else %}
	<h3 class="text-danger">No files selected, please go to your files and select files you want to perform the algorithm.</h3>
{% endif %}

{% endblock %}